---

## Title: ~/Documents/src/Ansible/ansible-rk1-cluster/tasks/grafana.yml
## Description: All tasks to deploy and manage Grafana in Docker Swarm
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2025-10-12 17:01:15
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


- name: 'Create network'
  community.docker.docker_network:
    name: 'grafana_backend'
    driver: 'overlay'
  tags:
    - grafana

- name: 'Create directory for container data'
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    owner: '{{ docker_user }}'
    group: '{{ docker_group }}'
    mode: '0777'
    state: 'directory'
  loop:
    - 'grafana-data'
    - 'grafana-data/db'
    - 'grafana-data/data'
    - 'grafana-data/dashboards'
    - 'grafana-config/'
    - 'grafana-config/etc'
  loop_control:
    loop_var: 'dir'
  tags:
    - grafana

- name: 'Remove grafana_db'
  community.docker.docker_swarm_service:
    name: 'grafana-db'
    state: absent
  tags:
    - grafana

- name: 'Deploy grafana DB'
  community.docker.docker_swarm_service:
    name: 'grafana-db'
    image: lscr.io/linuxserver/mariadb:latest
    hostname: grafana-db
    env:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=America/Chicago"
      - "MYSQL_ROOT_PASSWORD={{ vault_grafana_db_root_password }}" # Use a unique, secure password
      - "MYSQL_DATABASE=grafana"
      - "MYSQL_USER=grafana-user"
      - "MYSQL_PASSWORD={{ vault_grafana_db_password }}"
    mounts:
      - source: "{{ docker_data_dir }}/grafana-data/db"
        target: '/config'
        type: 'bind'
    networks:
      - 'grafana_backend'
    labels:
      traefik.enable: "false"
    mode: replicated
    replicas: 1
    restart_config:
      condition: "{{ restart_condition }}"
    placement:
      constraints:
        - 'node.platform.os == linux'
        - 'node.labels.bigmem == true'
  tags:
    - grafana

- name: 'Remove grafana'
  community.docker.docker_swarm_service:
    name: 'grafana'
    state: absent
    replicas: 0
  tags:
    - grafana
    - stop_all_services

- name: Copy configuration file
  template:
    src: grafana/defaults.ini.j2
    dest: "{{ docker_data_dir }}/grafana-config/etc/grafana.ini"
    mode: '0644'
    owner: '{{ docker_user }}'
    group: '{{ docker_group }}'
  tags:
    - grafana

- name: 'Deploy grafana'
  community.docker.docker_swarm_service:
    name: 'grafana'
    image: "grafana/grafana:{{ grafana_release }}"
    hostname: grafana
    force_update: true
    env:
      - "ServerName=grafana"
      - "TZ=America/Chicago"
      - "GF_PLUGINS_PREINSTALL=grafana-clock-panel,grafana-polystat-panel"
      - "GF_PATHS_CONFIG=/etc/grafana/grafana.ini"
    mounts:
      - source: "{{ docker_data_dir }}/grafana-data/data"
        target: '/var/lib/grafana'
        type: 'bind'
      - source: "{{ docker_data_dir }}/grafana-config/etc/grafana.ini"
        target: '/etc/grafana/grafana.ini'
        readonly: true
        type: 'bind'
      - source: '/etc/localtime'
        target: '/etc/localtime'
        type: 'bind'
        readonly: true
      - target: '/tmp'
        type: 'tmpfs'
    networks:
      - traefik_proxy
      - grafana_backend
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: Host(`{{ grafana_app_name }}.{{ traefik_domain_rk1 }}`)
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.entrypoints: websecure
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
      traefik.http.routers.grafana.tls.certresolver: "cloudflare"
    mode: 'replicated'
    replicas: 1
    restart_config:
      condition: "{{ restart_condition }}"
    placement:
      constraints:
        - 'node.platform.os == linux'
  no_log: "{{ not docker_service_debug }}"
  tags:
    - grafana