---

## Title: tasks/homepage.yml
## Description: Start/Stop homepage Service
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2025-09-15 09:38:42
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


- name: 'Create network'
  community.docker.docker_network:
    name: 'homepage_backend'
    driver: 'overlay'
    state: absent
  tags:
    - homepage

- name: 'Create directory for container data'
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    owner: '{{ docker_user }}'
    group: '{{ docker_user }}'
    mode: '0755'
    state: 'directory'
  loop:
    - 'homepage-config'
    - 'homepage-data'
    - 'homepage-data/images'
  loop_control:
    loop_var: 'dir'
  tags:
    - homepage

- name: 'Remove homepage'
  community.docker.docker_swarm_service:
    name: 'homepage'
    state: absent
    replicas: 0
  tags:
    - homepage
    - stop_all_services

- name: 'Deploy homepage'
  community.docker.docker_swarm_service:
    name: 'homepage'
    image: "ghcr.io/gethomepage/homepage:{{ homepage_release }}"
    hostname: homepage
    force_update: true
    env:
      - "ServerName=homepage"
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=America/Chicago"
      - "HOMEPAGE_ALLOWED_HOSTS={{ homepage_app_name }}.{{ traefik_domain_rk1 }}"
    mounts:
      - source: "{{ docker_data_dir }}/homepage-config"
        target: '/app/config/'
        type: 'bind'
      - source: "{{ docker_data_dir }}/homepage-data/images"
        target: '/app/public/images/'
        type: 'bind'
      - source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
        type: 'bind'
        readonly: true
    networks:
      - traefik_proxy
    publish:
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.rule: Host(`{{ homepage_app_name }}.{{ traefik_domain_rk1 }}`)
      traefik.http.routers.homepage.tls: "true"
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.tls.certresolver: "cloudflare"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"
    mode: 'replicated'
    replicas: 2
    restart_config:
      condition: "{{ restart_condition }}"
    placement:
      constraints:
        - 'node.platform.os == linux'
  no_log: "{{ not docker_service_debug }}"
  tags:
    - homepage
    - homepage_deploy
    - homepage_config
    - homepage_network
    - homepage_service
    - homepage_data
    - homepage_volume
    - homepage_container