middlewares:
    pihole-addprefix:
      addPrefix:
        prefix: /admin
    pihole-redirectregex:
      redirectRegex:
        regex: /admin/$
        replacement: /
    http:
      middlewares:
        redirect-to-https:
          redirectScheme:
            scheme: https
            permanent: true
        hsts-minimal:
          headers:
            stsSeconds: 31536000
            stsIncludeSubdomains: false
            stsPreload: false
            forceSTSHeader: true
        hsts-standard:
          headers:
            stsSeconds: 31536000
            stsIncludeSubdomains: true
            stsPreload: false
            forceSTSHeader: true
        hsts-full:
          headers:
            stsSeconds: 31536000
            stsIncludeSubdomains: true
            stsPreload: true
            forceSTSHeader: true
        # Redirect www URLs to their non-www equivalent
        # Use with traefik.http.routers.myRouter.middlewares: "redirect-www-to-non-www@file"
        # Source: https://www.benjaminrancourt.ca/how-to-redirect-from-non-www-to-www-with-traefik/
        redirect-www-to-non-www:
          # Redirect a request from an url to another with regex matching and replacement
          redirectregex:
            # Apply a permanent redirection (HTTP 301)
            permanent: true
            # The regular expression to match and capture elements from the request URL
            regex: "^https?://www\\.(.+)"
            # How to modify the URL to have the new target URL
            replacement: "https://${1}"
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
